calc/urls.py
from django.urls import path
from . import views

app_name = 'calc'
urlpatterns = [
	path('calc/', views.IndexView.as_view(), name='index'),
	path('', views.HomePage.as_view(), name='home'),
	path('terms/', views.Terms.as_view(), name='terms'),
	path('privacy/', views.Privacy.as_view(), name='privacy'),
	path('about/', views.About.as_view(), name='about'),
	path('new/', views.new, name='new'),
	path('<int:pk>/', views.DetailView.as_view(), name='detail'),
	path('<int:pk>/delete/', views.delete, name='delete'),
	path('<int:calc_id>/deceased', views.DeceasedCreate.as_view(), name='deceased'),
	path('<int:pk>/deceased_delete', views.DeceasedDelete.as_view(), name='deceased_delete'),
	path('<int:pk>/deceased_update', views.DeceasedUpdate.as_view(), name='deceased_update'),
	path('<int:pk>/calc_update', views.CalculationUpdate.as_view(), name='calc_update'),
	path('<int:calc_id>/mother', views.MotherCreate.as_view(), name='mother'),
	path('<int:pk>/heir_delete', views.HeirDelete.as_view(), name='heir_delete'),
	path('<int:pk>/heir_update', views.HeirUpdate.as_view(), name='heir_update'),
	path('<int:calc_id>/father', views.FatherCreate.as_view(), name='father'),
	path('<int:calc_id>/husband', views.HusbandCreate.as_view(), name='husband'),
	path('<int:calc_id>/wife', views.WifeCreate.as_view(), name='wife'),
	path('<int:calc_id>/daughter', views.DaughterCreate.as_view(), name='daughter'),
	path('<int:calc_id>/son', views.SonCreate.as_view(), name='son'),
	path('<int:calc_id>/bother', views.BrotherCreate.as_view(), name='brother'),
	path('<int:calc_id>/sister', views.SisterCreate.as_view(), name='sister'),
	path('<int:calc_id>/grandFather', views.GrandFatherCreate.as_view(), name='grandFather'),
	path('<int:calc_id>/grandMother', views.GrandMotherCreate.as_view(), name='grandMother'),
	path('<int:calc_id>/sonOfSon', views.SonOfSonCreate.as_view(), name='sonOfSon'),
	path('<int:calc_id>/daughterOfSon', views.DaughterOfSonCreate.as_view(), name='daughterOfSon'),
	path('<int:calc_id>/paternalSister', views.PaternalSisterCreate.as_view(), name='paternalSister'),
	path('<int:calc_id>/paternalBrother', views.PaternalBrotherCreate.as_view(), name='paternalBrother'),
	path('<int:calc_id>/maternalSister', views.MaternalSisterCreate.as_view(), name='maternalSister'),
	path('<int:calc_id>/maternalBrother', views.MaternalBrotherCreate.as_view(), name='maternalBrother'),
	path('<int:calc_id>/sonOfBrother', views.SonOfBrotherCreate.as_view(), name='sonOfBrother'),
	path('<int:calc_id>/sonOfPaternalBrother', views.SonOfPaternalBrotherCreate.as_view(), name='sonOfPaternalBrother'),
	path('<int:calc_id>/uncle', views.UncleCreate.as_view(), name='uncle'),
	path('<int:calc_id>/paternalUncle', views.PaternalUncleCreate.as_view(), name='paternalUncle'),
	path('<int:calc_id>/sonOfUncle', views.SonOfUncleCreate.as_view(), name='sonOfUncle'),
	path('<int:calc_id>/sonOfPaternalUncle', views.SonOfPaternalUncleCreate.as_view(), name='sonOfPaternalUncle'),
	path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
	path('<int:pk>/new-results/', views.NewResultsView.as_view(), name='new_results'),
	path('error/', views.error, name='error'),
	path('signup/', views.SignUp.as_view(), name='signup'),
]

mawareeth/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path
from calc import views as calc_views
from user_auth import views as user_auth_views

urlpatterns = [
    #path('admin/', admin.site.urls),
    #path('calc/', include('calc.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")),

]

calc_patterns = ([
    path('calc/', calc_views.IndexView.as_view(), name='index'),
    path('', calc_views.HomePage.as_view(), name='home'),
	path('terms/', calc_views.Terms.as_view(), name='terms'),
	path('privacy/', calc_views.Privacy.as_view(), name='privacy'),
    path('about/', calc_views.About.as_view(), name='about'),
    path('new/', calc_views.new, name='new'),
    path('<int:pk>/', calc_views.DetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', calc_views.delete, name='delete'),
    path('<int:calc_id>/deceased', calc_views.DeceasedCreate.as_view(), name='deceased'),
	path('<int:pk>/deceased_delete', calc_views.DeceasedDelete.as_view(), name='deceased_delete'),
	path('<int:pk>/deceased_update', calc_views.DeceasedUpdate.as_view(), name='deceased_update'),
	path('<int:pk>/calc_update', calc_views.CalculationUpdate.as_view(), name='calc_update'),
    path('<int:calc_id>/mother', calc_views.MotherCreate.as_view(), name='mother'),
	path('<int:pk>/heir_delete', calc_views.HeirDelete.as_view(), name='heir_delete'),
	path('<int:pk>/heir_update', calc_views.HeirUpdate.as_view(), name='heir_update'),
    path('<int:calc_id>/father', calc_views.FatherCreate.as_view(), name='father'),
	path('<int:calc_id>/husband', calc_views.HusbandCreate.as_view(), name='husband'),
	path('<int:calc_id>/wife', calc_views.WifeCreate.as_view(), name='wife'),
	path('<int:calc_id>/daughter', calc_views.DaughterCreate.as_view(), name='daughter'),
	path('<int:calc_id>/son', calc_views.SonCreate.as_view(), name='son'),
	path('<int:calc_id>/bother', calc_views.BrotherCreate.as_view(), name='brother'),
	path('<int:calc_id>/sister', calc_views.SisterCreate.as_view(), name='sister'),
	path('<int:calc_id>/grandFather', calc_views.GrandFatherCreate.as_view(), name='grandFather'),
	path('<int:calc_id>/grandMother', calc_views.GrandMotherCreate.as_view(), name='grandMother'),
	path('<int:calc_id>/sonOfSon', calc_views.SonOfSonCreate.as_view(), name='sonOfSon'),
	path('<int:calc_id>/daughterOfSon', calc_views.DaughterOfSonCreate.as_view(), name='daughterOfSon'),
	path('<int:calc_id>/paternalSister', calc_views.PaternalSisterCreate.as_view(), name='paternalSister'),
	path('<int:calc_id>/paternalBrother', calc_views.PaternalBrotherCreate.as_view(), name='paternalBrother'),
	path('<int:calc_id>/maternalSister', calc_views.MaternalSisterCreate.as_view(), name='maternalSister'),
	path('<int:calc_id>/maternalBrother', calc_views.MaternalBrotherCreate.as_view(), name='maternalBrother'),
	path('<int:calc_id>/sonOfBrother', calc_views.SonOfBrotherCreate.as_view(), name='sonOfBrother'),
	path('<int:calc_id>/sonOfPaternalBrother', calc_views.SonOfPaternalBrotherCreate.as_view(), name='sonOfPaternalBrother'),
	path('<int:calc_id>/uncle', calc_views.UncleCreate.as_view(), name='uncle'),
	path('<int:calc_id>/paternalUncle', calc_views.PaternalUncleCreate.as_view(), name='paternalUncle'),
	path('<int:calc_id>/sonOfUncle', calc_views.SonOfUncleCreate.as_view(), name='sonOfUncle'),
	path('<int:calc_id>/sonOfPaternalUncle', calc_views.SonOfPaternalUncleCreate.as_view(), name='sonOfPaternalUncle'),
    path('<int:pk>/results/', calc_views.ResultsView.as_view(), name='results'),
    path('<int:pk>/new-results/', calc_views.NewResultsView.as_view(), name='new_results'),
    path('error/', calc_views.error, name='error'),
    path('signup/', calc_views.SignUp.as_view(), name='signup'),


], 'calc')

user_auth_patterns = ([
    path('profile/', user_auth_views.profile, name='profile')
], 'user_auth')
urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include(calc_patterns,namespace='calc')),
    path('',include(user_auth_patterns,namespace='user_auth')),
)

calc/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import View
from django.contrib import messages
from user_auth.forms import UserCreationForm
from django.urls import reverse_lazy
from calc.forms import HeirForm, DeceasedForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils.translation import gettext as _
from django.views.generic.base import TemplateView
from .models import *
from waffle.mixins import WaffleFlagMixin, WaffleSwitchMixin

import waffle


class HomePage(TemplateView):
	template_name="calc/home.html"

	def get(self, request, **kwargs):
		if request.user.is_authenticated:
			return HttpResponseRedirect(reverse( 'calc:index'))
		else:
			context = self.get_context_data(**kwargs)
			return self.render_to_response(context)
class Terms(TemplateView):
	template_name="calc/terms.html"
class Privacy(TemplateView):
	template_name="calc/privacy.html"
class About(TemplateView):
	template_name="calc/about.html"
class DeceasedCreate(CreateView):
	model = Deceased
	fields = ['first_name','last_name','sex', 'estate']

	def dispatch(self, request, *args, **kwargs):
		"""
		Overridden so we can make sure the `calc` instance exists
		before going any further.
		"""
		self.calc = get_object_or_404(Calculation, pk=kwargs['calc_id'])
		if self.calc.deceased_set.count() >= 1:
			messages.error(request,_("Decease already exist"))
			return HttpResponseRedirect(reverse( 'calc:error'))
		return super().dispatch(request, *args, **kwargs)
	def form_valid(self, form):
		"""
		Overridden to add the relation to the calculation instance.
		"""
		form.instance.calc = self.calc
		return super().form_valid(form)

class DeceasedUpdate(UpdateView):
	model = Deceased
	fields = ['first_name','last_name', 'estate']

class DeceasedDelete(DeleteView):
	model = Deceased
	def delete(self, request, *args, **kwargs):
		self.object = self.get_object()
		self.calc = self.object.calc # assuming that deceased have a foreignkey reference to Calculation model
		self.calc.heir_set.all().delete()
		self.object.delete()
		success_url = self.get_success_url()
		return HttpResponseRedirect(success_url)

	def get_success_url(self):
		calc = self.calc
		return reverse(  # no need for lazy here
			'calc:detail',
			 kwargs={'pk': calc.id}
		)
class MotherCreate(CreateView):
	model = Mother
	fields = ['first_name','last_name']
	template_name = 'calc/heir_form.html'

	def dispatch(self, request, *args, **kwargs):
		"""
		Overridden so we can make sure the `calc` instance exists
		before going any further.
		"""
		self.calc = get_object_or_404(Calculation, pk=kwargs['calc_id'])
		if self.calc.heir_set.instance_of(Mother).count() >= 1:
			messages.error(request,_("Mother already exist"))
			return HttpResponseRedirect(reverse( 'calc:error'))
		return super().dispatch(request, *args, **kwargs)

	def form_valid(self, form):
		"""
		Overridden to add the relation to the calculation instance.
		"""
		form.instance.calc = self.calc
		self.object = form.save()
		self.object.sex="F"
		self.object.save()
		form.instance.calc.add_mother(self.object)
		return super().form_valid(form)

class FatherCreate(CreateView):
	model = Father
	fields = ['first_name','last_name']
	template_name = 'calc/heir_form.html'

	def dispatch(self, request, *args, **kwargs):
		"""
		Overridden so we can make sure the `calc` instance exists
		before going any further.
		"""
		self.calc = get_object_or_404(Calculation, pk=kwargs['calc_id'])
		if self.calc.heir_set.instance_of(Father).count() >= 1:
			messages.error(request,_("Father already exist"))
			return HttpResponseRedirect(reverse( 'calc:error'))
		return super().dispatch(request, *args, **kwargs)

	def form_valid(self, form):
		"""
		Overridden to add the relation to the calculation instance.
		"""
		form.instance.calc = self.calc
		self.object = form.save()
		self.object.sex="M"
		self.object.save()
		form.instance.calc.add_father(self.object)
		return super().form_valid(form)

class HusbandCreate(CreateView):
	model = Husband
	fields = ['first_name','last_name']
	template_name = 'calc/heir_form.html'

	def dispatch(self, request, *args, **kwargs):
		"""
		Overridden so we can make sure the `calc` instance exists
		before going any further.
		"""
		self.calc = get_object_or_404(Calculation, pk=kwargs['calc_id'])
		if self.calc.heir_set.instance_of(Husband).count() >= 1:
			messages.error(request,_("Husband already exist"))
			return HttpResponseRedirect(reverse( 'calc:error'))
		return super().dispatch(request, *args, **kwargs)

	def form_valid(self, form):
		"""
		Overridden to add the relation to the calculation instance.
		"""
		form.instance.calc = self.calc
		self.object = form.save()
		self.object.sex="M"
		self.object.save()
		form.instance.calc.add_husband(self.object)
		return super().form_valid(form)

class WifeCreate(CreateView):
	model = Wife
	fields = ['first_name','last_name']
	template_name = 'calc/heir_form.html'

	def dispatch(self, request, *args, **kwargs):
		"""
		Overridden so we can make sure the `calc` instance exists
		before going any further.
		"""
		self.calc = get_object_or_404(Calculation, pk=kwargs['calc_id'])
		if self.calc.heir_set.instance_of(Wife).count() >= 4:
			messages.error(request,_("Cann't have more than 4 wifes"))
			return HttpResponseRedirect(reverse( 'calc:error'))
		return super().dispatch(request, *args, **kwargs)

	def form_valid(self, form):
		"""
		Overridden to add the relation to the calculation instance.
		"""
		form.instance.calc = self.calc
		self.object = form.save()
		self.object.sex="F"
		self.object.save()
		form.instance.calc.add_wife(self.object)
		return super().form_valid(form)

class DaughterCreate(CreateView):
	model = Daughter
	fields = ['first_name','last_name']
	template_name = 'calc/heir_form.html'

	def dispatch(self, request, *args, **kwargs):
		"""
		Overridden so we can make sure the `calc` instance exists
		before going any further.
		"""
		self.calc = get_object_or_404(Calculation, pk=kwargs['calc_id'])
		return super().dispatch(request, *args, **kwargs)

	def form_valid(self, form):
		"""
		Overridden to add the relation to the calculation instance.
		"""
		form.instance.calc = self.calc
		self.object = form.save()
		self.object.sex ="F"
		self.object.save()
		if form.instance.calc.deceased_set.first().sex =='M':
			father = form.instance.calc.deceased_set.first()
			if form.instance.calc.deceased_set.first().male_marriages.count()==1:
				mother =form.instance.calc.deceased_set.first().male_marriages.first().female
			elif form.instance.calc.deceased_set.first().male_marriages.count()==0:
				mother = None
			else:
				mother = get_object_or_404(Wife, pk=self.request.POST.get('mother'))
		else:
			 mother = form.instance.calc.deceased_set.first()
			 if form.instance.calc.deceased_set.first().female_marriages.count()==1:
				 father = form.instance.calc.deceased_set.first().female_marriages.first().male
			 else:
				 father = None
		form.instance.calc.add_daughter(self.object, mother=mother, father=father)
		return super().form_valid(form)

class SonCreate(CreateView):
	model = Son
	fields = ['first_name','last_name']
	template_name = 'calc/heir_form.html'

	def dispatch(self, request, *args, **kwargs):
		"""
		Overridden so we can make sure the `calc` instance exists
		before going any further.
		"""
		self.calc = get_object_or_404(Calculation, pk=kwargs['calc_id'])
		return super().dispatch(request, *args, **kwargs)

	def form_valid(self, form):
		"""
		Overridden to add the relation to the calculation instance.
		"""
		form.instance.calc = self.calc
		self.object = form.save()
		self.object.sex="M"
		self.object.save()
		if form.instance.calc.deceased_set.first().sex =='M':
			father = form.instance.calc.deceased_set.first()
			if form.instance.calc.deceased_set.first().male_marriages.count()==1:
				mother =form.instance.calc.deceased_set.first().male_marriages.first().female
			elif form.instance.calc.deceased_set.first().male_marriages.count()==0:
				mother = None
			else:
				mother = get_object_or_404(Wife, pk=self.request.POST.get('mother'))
		else:
			 mother = form.instance.calc.deceased_set.first()
			 if form.instance.calc.deceased_set.first().female_marriages.count()==1:
				 father = form.instance.calc.deceased_set.first().female_marriages.first().male
			 else:
				 father = None
		form.instance.calc.add_son(self.object, mother=mother, father=father)
		return super().form_valid(form)

class BrotherCreate(WaffleFlagMixin, CreateView):
	model = Brother
	fields = ['first_name','last_name']
	template_name = 'calc/heir_form.html'
	waffle_flag = "Brother"

	def dispatch(self, request, *args, **kwargs):
		"""
		Overridden so we can make sure the `calc` instance exists
		before going any further.
		"""
		self.calc = get_object_or_404(Calculation, pk=kwargs['calc_id'])
		return super().dispatch(request, *args, **kwargs)

	def form_valid(self, form):
		"""
		Overridden to add the relation to the calculation instance.
		"""
		form.instance.calc = self.calc
		self.object = form.save()
		self.object.sex="M"
		self.object.save()
		form.instance.calc.add_brother(self.object)
		return super().form_valid(form)

class SisterCreate(WaffleFlagMixin, CreateView):
	model = Sister
	fields = ['first_name','last_name']
	template_name = 'calc/heir_form.html'
	waffle_flag = "Sister"

	def dispatch(self, request, *args, **kwargs):
		"""
		Overridden so we can make sure the `calc` instance exists
		before going any further.
		"""
		self.calc = get_object_or_404(Calculation, pk=kwargs['calc_id'])
		return super().dispatch(request, *args, **kwargs)

	def form_valid(self, form):
		"""

calc/templates/calc/base.html
{% load i18n %}
{% load static %}
{% load active_link_tags %}
<!doctype html>
{% if LANGUAGE_BIDI %}
<html lang="en" dir="rtl">
{% else %}
<html lang="en">
{% endif %}
<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-30659565-1"></script>
  <script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-30659565-1');
  </script>

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  {% get_current_language_bidi as LANGUAGE_BIDI %}
  {% if LANGUAGE_BIDI %}
  <link rel="stylesheet" href="https://cdn.rtlcss.com/bootstrap/v4.2.1/css/bootstrap.min.css" integrity="sha384-vus3nQHTD+5mpDiZ4rkEPlnkcyTP+49BhJ4wJeJunw06ZAp+wzzeBPUXr42fi8If" crossorigin="anonymous">
  {% else %}
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  {% endif %}
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'calc/css/content.css' %}">
  <link rel="shortcut icon" type="image/png" href="{% static 'calc/img/favicon.ico' %}"/>

  {% block css %}{% endblock %}

  <title>{% block title %}{% endblock %} | {% trans "Mawareeth" %} {{ APP_VERSION }}</title>
</head>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'calc:index' %}"> {% trans "Mawareeth 2.0" %} </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% active_link 'calc:home' strict=True %}">
        <a class="nav-link" href="{% url 'calc:home' %}"> {% trans "Home" %} <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% active_link 'calc:index' %}">
        <a class="nav-link" href="{% url 'calc:index' %}"> {% trans "Calculations" %} </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'calc:about' %}"> {% trans "About" %} </a>
      </li>
    </ul>
    {% if user.is_authenticated %}
    {% trans "Welcome " %}
    <a href="{% url 'user_auth:profile' %}">{{ user.username }}</a>
    -- <a href="{% url 'logout' %}">{% trans " logout " %}</a>
    {% else %}
    <a href="{% url 'login' %}">{% trans 'login' %}</a> |
    <a href="{% url 'calc:signup' %}">{% trans 'Sign Up' %}</a>

    {% endif %}
    <form class="form-inline my-2 my-lg-0" action="{% url 'set_language' %}" method="post">{% csrf_token %}
      <input name="next" type="hidden" value="{{ redirect_to }}">
      <select name="language">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
        <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
          {{ language.name_local }} ({{ language.code }})
        </option>
        {% endfor %}
      </select>
      <input type="submit" value="Go">
    </form>
  </div>
</nav>
<body>
  {% if messages %}
  <div class="messages">
    {% for message in messages %}
    <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
  </div>
  {% endif %}
  {% block header%} {% endblock %}
  <main role="main" class="container">
  {% block body %}{% endblock %}
  </main>

  <footer class="footer">
      <div class="container">
        <a href="{% url 'calc:terms' %}">
          {% trans "Terms and Conditions" %}
        </a> |
        <a href="{% url 'calc:privacy' %}">
          {% trans "Privacy Policy" %}
        </a>
      </div>
    </footer>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  {% get_current_language_bidi as LANGUAGE_BIDI %}
  {% if LANGUAGE_BIDI %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://cdn.rtlcss.com/bootstrap/v4.2.1/js/bootstrap.min.js" integrity="sha384-a9xOd0rz8w0J8zqj1qJic7GPFfyMfoiuDjC9rqXlVOcGO/dmRqzMn34gZYDTel8k" crossorigin="anonymous"></script>
  {% else %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  {% endif %}
  {% block scripts %}
  {% endblock %}
</body>
</html>

calc/templates/calc/calculation_form.html
{% extends "calc/base.html" %}
{% load static %}
{% load i18n %}
{% load calc_extras %}
{% load crispy_forms_tags %}
{% block title %}
{% trans "Calculation" %}
{% endblock %}
{% block body %}
<div class="container">
  <div class="row">
    <div class="col-sm-10 col-md-9 col-lg-7 mx-auto">
      <div class="card card-index my-5">
        <div class="card-header">
        </div>
        <div class="card-body">
          <form method="post"
          action="{{request.path}}">
          {% csrf_token %}
          {{ form|crispy }}
          <input type="submit" class="btn btn-primary">
        </form>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock %}

calc/templates/calc/error.html
{% extends "calc/base.html" %}
{% load static %}
{% load i18n %}
{% block title %}
{% trans "error" %}
{% endblock %}
{% block body %}
<div class="container">
  <div class="row">
    <div class="bg-white col-sm-12 col-md-12 col-lg-12 mx-auto">
      <div class="container">
        {% if messages %}
        <div class="span12">
          {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
            {{ message|safe }}
          </div>
          {% endfor %}
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

calc/templates/calc/index.html
{% extends "calc/base.html" %}
{% load static %}
{% load i18n %}
{% load icons %}
{% load waffle_tags %}

{% block title %}
{% trans "Calculations" %}
{% endblock %}
{% block body %}
<div class="container">
  <div class="row">
    <div class="col-sm-10 col-md-9 col-lg-7 mx-auto">
      <div class="card card-index my-5">
        <div class="card-body">
          <h5 class="card-title text-center">{% trans "Create new calculation"%}</h5>
          <form class="form-signin" action="{% url 'calc:new' %}" method="post">
            {% csrf_token %}
            <div class="form-label-group">
              <input id="name" type="text" name="name" placeholder="{% trans 'Name your Calculation' %}" class="form-control"> </input>
              <label for="name">{% trans "Calculation name" %}</label>
            </div>
            <input class="btn btn-primary" type="submit" name="next" value="{% trans 'Submit and continue' %}"></input>
            <input class="btn btn-primary float-right" type="submit" name="stay" value="{% trans 'Save and add another' %}"></input>

          </form>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="row">
  <div class="col-sm-10 col-md-9 col-lg-7 mx-auto">

    <ul class="list-group">
      {% if calculation_list %}
      {% for calculation in calculation_list %}
      <li class="list-group-item">
        {% flag "new_results" %}
        <a href="{% url 'calc:new_results' calculation.id %}"> {{calculation.name}}
      </a>
      {% else %}
      <a href="{% url 'calc:results' calculation.id %}"> {{calculation.name}}
    </a>
    {% endflag %}


    <a href="{% url 'calc:delete' calculation.id %}"
    class="float-right btn btn-primary a-btn-slide-text">
    <span>{% icon 'trash-o' %}</span>
  </a>
  <a href="{% url 'calc:detail' calculation.id %}"
  class="float-right btn btn-primary a-btn-slide-text">
  <span>{% icon 'edit' %}</span>
</a>
</li>
{% endfor %}
{% else %}
<li class="list-group-item">No calculation available.</li>
{% endif %}
</ul>
</div>
</div>
{% endblock %}